global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'prometheus-monitor'

rule_files:
#   - "/var/app/prometheus/alert.rules"

scrape_configs:
- job_name: 'prometheus'
  scrape_interval: 5s
  static_configs:
  - targets:
    - 'localhost:9090'

